# Generated by Django 5.2.6 on 2025-10-12 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('category', models.CharField(blank=True, choices=[('travel', '外出（旅行）'), ('shopping', 'ショッピング'), ('hobby', '趣味'), ('other', 'その他')], max_length=20, verbose_name='カテゴリ')),
                ('difficulty', models.CharField(blank=True, choices=[('high', '高'), ('medium', '中'), ('low', '低')], max_length=10, verbose_name='難易度')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('done', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done', 'deadline', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'done', 'deadline'], name='todo_app_wa_user_id_1ec673_idx')],
            },
        ),
    ]
