# Generated by Django 5.2.6 on 2025-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='want',
            name='todo_app_wa_user_id_1ec673_idx',
        ),
        migrations.AddField(
            model_name='want',
            name='memo',
            field=models.CharField(blank=True, max_length=120, verbose_name='メモ'),
        ),
    ]
