# Generated by Django 5.2.6 on 2025-10-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_want_todo_app_wa_user_id_1ec673_idx_want_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完了日時'),
        ),
    ]
