# Generated by Django 5.1.3 on 2025-10-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0003_want_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="want",
            name="title",
            field=models.CharField(max_length=64, verbose_name="タイトル"),
        ),
    ]
